# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 04:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaliyBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=32)),
                ('total', models.IntegerField()),
                ('sts', models.CharField(max_length=1)),
                ('sts_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daliybath_store', to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='DaliyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_id', models.CharField(max_length=32)),
                ('nick_name', models.CharField(max_length=32)),
                ('num', models.FloatField(max_length=9)),
                ('sts', models.CharField(max_length=1)),
                ('sts_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daliydetail_daliybatch', to='store.DaliyBatch')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daliy_item', to='store.Item')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daliydetail_store', to='store.Store')),
            ],
        ),
        migrations.RemoveField(
            model_name='daliy',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='daliy',
            name='store',
        ),
        migrations.DeleteModel(
            name='Daliy',
        ),
    ]
