# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-13 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_staff_staffstorerel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_code', models.CharField(max_length=32)),
                ('config_value', models.CharField(max_length=32)),
                ('sts', models.CharField(max_length=1)),
                ('sts_date', models.DateTimeField(auto_now_add=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='password',
            field=models.CharField(default=123456, max_length=32),
            preserve_default=False,
        ),
    ]
